In [6]:
import pandas as pd
df = pd.read_csv(r"C:\Users\mukka\Downloads\HealthcareDataset1.csv")

In [8]:
df.head()

,PatientID,PatientName,Age,Gender,BloodType,Diagnosis,Treatment,AdmissionDate,DischargeDate,TotalBill,Full Prescription Details
0,1,David Johnson,3,Other,A+,Flu,Medication,2021-01-01 00:00:00,2021-01-02 00:00:00,14383.782350,"Furosemide 40mg, three times a day for 5 days;..."
1,2,NaN,82,Other,A-,Covid-19,Medication,2021-01-02 00:00:00,2021-01-03 00:00:00,15512.302210,"Losartan 50mg, twice a day for 7 days; Amoxici..."
2,3,William Taylor,56,Other,B+,Hypertension,Therapy,2021-01-03 00:00:00,2021-01-04 00:00:00,4039.296436,"Amlodipine 5mg, twice a day for 5 days; Gabape..."
3,4,William Davis,36,Other,AB+,Covid-19,Therapy,2021-01-04 00:00:00,2021-01-05 00:00:00,4226.498069,"Azithromycin 250mg, three times a day as neede..."
4,5,Robert Davis,78,Male,B+,Flu,Surgery,2021-01-05 00:00:00,2021-01-06 00:00:00,2562.768983,"Duloxetine 60mg, three times a day for 5 days;..."

In [9]:
df.describe()

         PatientID          Age     TotalBill
count  1000.000000  1000.000000    940.000000
mean    500.500000    50.500000  10038.866970
std     288.819436    28.599859   5801.795268
min       1.000000     0.000000    200.928022
25%     250.750000    26.000000   4883.315196
50%     500.500000    51.500000  10152.880440
75%     750.250000    75.000000  14872.452167
max    1000.000000    99.000000  19979.201530

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   PatientID                  1000 non-null   int64
 1   PatientName                940 non-null    object
 2   Age                        1000 non-null   int64
 3   Gender                     1000 non-null   object
 4   BloodType                  1000 non-null   object
 5   Diagnosis                  1000 non-null   object
 6   Treatment                  1000 non-null   object
 7   AdmissionDate              1000 non-null   object
 8   DischargeDate              1000 non-null   object
 9   TotalBill                  940 non-null    float64
 10  Full Prescription Details  1000 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 86.1+ KB

In [17]:
df["PatientName"].isnull().sum()

np.int64(60)

In [31]:
df = df.dropna(subset = ["PatientName"])

In [27]:
df["TotalBill"] = df["TotalBill"].fillna(10038.866970)

In [28]:
df["TotalBill"].isnull().sum()

np.int64(0)

In [32]:
df["PatientName"].isnull().sum()

np.int64(0)

In [35]:
df["AdmissionDate"] = pd.to_datetime(df["AdmissionDate"])

C:\Users\mukka\AppData\Local\Temp\ipykernel_29840\3116005961.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["AdmissionDate"] = pd.to_datetime(df["AdmissionDate"])

In [36]:
df["AdmissionDate"].dtype

dtype('<M8[ns]')

In [37]:
df["DischargeDate"] = pd.to_datetime(df["DischargeDate"])

C:\Users\mukka\AppData\Local\Temp\ipykernel_29840\1657332283.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["DischargeDate"] = pd.to_datetime(df["DischargeDate"])

In [39]:
df["DischargeDate"].dtype

dtype('<M8[ns]')

In [40]:
df.head()

,PatientID,PatientName,Age,Gender,BloodType,Diagnosis,Treatment,AdmissionDate,DischargeDate,TotalBill,Full Prescription Details
0,1,David Johnson,3,Other,A+,Flu,Medication,2021-01-01,2021-01-02,14383.782350,"Furosemide 40mg, three times a day for 5 days;..."
2,3,William Taylor,56,Other,B+,Hypertension,Therapy,2021-01-03,2021-01-04,4039.296436,"Amlodipine 5mg, twice a day for 5 days; Gabape..."
3,4,William Davis,36,Other,AB+,Covid-19,Therapy,2021-01-04,2021-01-05,4226.498069,"Azithromycin 250mg, three times a day as neede..."
4,5,Robert Davis,78,Male,B+,Flu,Surgery,2021-01-05,2021-01-06,2562.768983,"Duloxetine 60mg, three times a day for 5 days;..."
5,6,Susan Taylor,18,Female,B+,Diabetes,Medication,2021-01-06,2021-01-07,10407.382990,"Escitalopram 10mg, twice a day for 7 days; Flu..."

In [44]:
df.to_csv(r"C:\Users\mukka\Downloads\Healthcare_Cleaned.csv", index=False)